AWSTemplateFormatVersion: "2010-09-09"

Description: 'Main Stack combining Networking, Security, and Compute stacks. With Nested format.'

Parameters:
  VPCName:
    Description: The name of the VPC being created.
    Type: String
    Default: 'NT548-CFN-VPC'

  KeyNamePublic:
    Description: 'The name of an existing EC2 KeyPair to enable SSH access to the public instance. This KeyPair must already exist in the AWS region.'
    Type: AWS::EC2::KeyPair::KeyName
    Default: 'haudt-pub-key'

  KeyNamePrivate:
    Description: 'The name of an existing EC2 KeyPair to enable SSH access to the private instance. This KeyPair must already exist in the AWS region.'
    Type: AWS::EC2::KeyPair::KeyName
    Default: 'haudt-priv-key'

  InstanceType:
    Description: 'Choose the instance type'
    Type: String
    Default: 't2.micro'
    AllowedValues:
      - t2.nano
      - t2.micro
      - t2.small
      - t2.medium
      - t2.large
      - t2.xlarge
      - t2.2xlarge
      - t3.nano
      - t3.micro
      - t3.small
      - t3.medium
      - t3.large
      - t3.xlarge
      - t3.2xlarge
      - m4.large
      - m4.xlarge
      - m4.2xlarge
      - m4.4xlarge
      - m4.10xlarge
      - m5.large
      - m5.xlarge
      - m5.2xlarge
      - m5.4xlarge
      - c5.large
      - c5.xlarge
      - c5.2xlarge
      - c5.4xlarge
      - c5.9xlarge
      - g3.8xlarge
      - r5.large
      - r5.xlarge
      - r5.2xlarge
      - r5.4xlarge
      - i3.xlarge
      - i3.2xlarge
      - i3.4xlarge
      - i3.8xlarge
      - d2.xlarge
      - d2.2xlarge
      - d2.4xlarge
      - d2.8xlarge

  AllowedSSHIP1:
    Description: 'User IP address (in CIDR notation) allowed to SSH into the public EC2 instance.'
    Type: String
    Default: ''
    

  AllowedSSHIP2:
    Description: 'User IP address (in CIDR notation) allowed to SSH into the public EC2 instance.'
    Type: String
    Default: ''

Resources:
  NetworkStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://s3.amazonaws.com/haudt-cfn-lab2/networking.yaml
      Parameters:
        VPCName: !Ref VPCName
      TimeoutInMinutes: 10

  SecurityStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://s3.amazonaws.com/haudt-cfn-lab2/security.yaml
      Parameters:
        VPC: !GetAtt NetworkStack.Outputs.VPCId
        PublicSubnetID: !GetAtt NetworkStack.Outputs.PublicSubnet0
        AllowedSSHIP1: !Ref AllowedSSHIP1
        AllowedSSHIP2: !Ref AllowedSSHIP2
      TimeoutInMinutes: 10

  EC2Stack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://s3.amazonaws.com/haudt-cfn-lab2/compute.yaml
      Parameters:
        Name: !Ref VPCName
        KeyNamePublic: !Ref KeyNamePublic
        KeyNamePrivate: !Ref KeyNamePrivate
        LatestAmiId: /aws/service/ami-amazon-linux-latest/amzn2-ami-hvm-x86_64-gp2
        VPC: !GetAtt NetworkStack.Outputs.VPCId
        PublicSubnetID: !GetAtt NetworkStack.Outputs.PublicSubnet0
        PrivateSubnetID: !GetAtt NetworkStack.Outputs.PrivateSubnet0
        SecurityGroupPublicInstanceID: !GetAtt SecurityStack.Outputs.SecurityGroupPublicInstanceId
        SecurityGroupPrivateInstanceID: !GetAtt SecurityStack.Outputs.SecurityGroupPrivateInstanceId
        InstanceType: !Ref InstanceType
      TimeoutInMinutes: 10

Outputs:
  VPCId:
    Description: VPC ID from Network Stack
    Value: !GetAtt NetworkStack.Outputs.VPCId

  PublicSubnet0:
    Description: Public Subnet ID from Network Stack
    Value: !GetAtt NetworkStack.Outputs.PublicSubnet0

  PrivateSubnet0:
    Description: Private Subnet ID from Network Stack
    Value: !GetAtt NetworkStack.Outputs.PrivateSubnet0

  SecurityGroupPublicInstanceId:
    Description: Security Group ID for the public instance from Security Stack
    Value: !GetAtt SecurityStack.Outputs.SecurityGroupPublicInstanceId

  SecurityGroupPrivateInstanceId:
    Description: Security Group ID for the private instance from Security Stack
    Value: !GetAtt SecurityStack.Outputs.SecurityGroupPrivateInstanceId

  EC2PublicInstanceId:
    Description: EC2 Public Instance ID
    Value: !GetAtt EC2Stack.Outputs.EC2PublicInstanceId

  EC2PrivateInstanceId:
    Description: EC2 Private Instance ID
    Value: !GetAtt EC2Stack.Outputs.EC2PrivateInstanceId
